[tools]
python = ["3.12.0", "3.13.0", "3.14.0"]
rust = "latest"
node = "latest"
go = "latest"
terraform = "latest"
bun = "latest"

trivy = "latest"
uv = "latest"
act = "latest"
actionlint = "latest"
pre-commit = "latest"
bat = "latest"
bottom = "latest"
eza = "latest"
ripgrep = "latest"
hadolint = "latest"
dust = "latest"
github-cli = "latest"
delta = "latest"
starship = "latest"
tflint = "latest"
packer = "latest"
gcloud = "latest"
tilt = "latest"
claude-code = "latest"
gemini-cli = "latest"

"npm:@openai/codex" = "latest"
"npm:@sasazame/ccresume" = "latest"
"npm:ccusage" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.npm]
bun = true