[tools]
python = ["3.12.0", "3.13.0", "3.14.0"]
rust = "latest"
node = "latest"
go = "latest"
terraform = "latest"
bun = "latest"

trivy = "latest"
uv = "latest"
act = "latest"
actionlint = "latest"
pre-commit = "latest"
bat = "latest"
bottom = "latest"
eza = "latest"
ripgrep = "latest"
hadolint = "latest"
dust = "latest"
github-cli = "latest"
delta = "latest"
starship = "latest"
tflint = "latest"
packer = "latest"
gcloud = "latest"
tilt = "latest"
claude-code = "latest"
gemini-cli = "latest"
ghq = "latest"
copier = "latest"
fzf ="latest"
"github:trasta298/keifu" = "latest"
atuin = "latest"
zoxide = "latest"
helix = "latest"

"npm:@sasazame/ccresume" = "latest"
"npm:ccusage" = "latest"
"npm:agent-browser" = "latest"
"npm:difit" = "latest"
"npm:svelte-language-server" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.npm]
bun = true

[tasks.go-tools]
description = "Install Go CLI tools"
run = [
    "go install github.com/d-kuro/gwq/cmd/gwq@latest"
]
